"""
services_config_v2.py — Enhanced service registry with run modes & dependencies.
Upgrade from v1: adds run_mode, idle_timeout_s, dependencies, critical flag,
and startup_grace_s for each service.

Run Modes:
  ALWAYS_ON   — 24/7, auto-restart with exponential backoff
  ON_DEMAND   — Start on tool call, stop after idle timeout
  SCHEDULED   — Start on cron, stop when done
  MANUAL      — Only via dashboard/API
  MAINTENANCE — Intentionally down, alerts suppressed
  VACATION    — Global: only critical ALWAYS_ON services run
"""

from typing import Literal

RunMode = Literal["always_on", "on_demand", "scheduled", "manual", "maintenance"]

# ── Group Metadata ─────────────────────────────────────────────────

GROUP_META = {
    "gateway": {
        "name": "Gateway & Routing",
        "description": "Core request routing, auth, and transport layers",
        "icon": "🚪",
        "color": "#58a6ff",
        "priority": 1,  # Highest — everything depends on this
    },
    "security": {
        "name": "Security & Secrets",
        "description": "Vault access, key management, audit logging",
        "icon": "🔐",
        "color": "#f0883e",
        "priority": 1,
    },
    "comms": {
        "name": "Communications",
        "description": "Phone, SMS, voice synthesis, messaging",
        "icon": "📞",
        "color": "#a371f7",
        "priority": 3,
    },
    "tools": {
        "name": "Tool Servers",
        "description": "MCP tool servers: CRM, scraping, maps, e-commerce",
        "icon": "🔧",
        "color": "#3fb950",
        "priority": 3,
    },
    "orchestration": {
        "name": "Orchestration",
        "description": "Business logic orchestrators: 500GL ops, workflows",
        "icon": "🎯",
        "color": "#d29922",
        "priority": 2,
    },
    "background": {
        "name": "Background Services",
        "description": "Bots, sync agents, periodic tasks",
        "icon": "⚙️",
        "color": "#8b949e",
        "priority": 4,
    },
    "monitoring": {
        "name": "Monitoring & Metrics",
        "description": "Prometheus exporters, health dashboards",
        "icon": "📊",
        "color": "#79c0ff",
        "priority": 2,
    },
}

# ── Dependency Graph ───────────────────────────────────────────────
# If a dependency is down, the dependent is marked BLOCKED, not FAILED.

DEPENDENCIES = {
    # Every MCP tool depends on gateway for routing
    "gateway-mcp-http":      ["mcp-gateway"],
    "designer-agent":        ["mcp-gateway", "key-custodian"],
    "firecrawl-mcp":         ["mcp-gateway"],
    "mapbox-mcp":            ["mcp-gateway"],
    "vtiger-api":            ["mcp-gateway", "key-custodian"],
    "boldsign-agent":        ["mcp-gateway", "key-custodian"],
    "twilio-mcp":            ["mcp-gateway", "key-custodian"],
    "elevenlabs-mcp":        ["mcp-gateway", "key-custodian"],
    "telnyx-mcp":            ["mcp-gateway", "key-custodian"],
    "woocommerce-mcp":       ["mcp-gateway", "key-custodian"],
    "500gl-orchestrator-ws": ["mcp-gateway", "key-custodian"],
    # Monitoring chain
    "alertmanager":          ["prometheus"],
    "grafana":               ["prometheus"],
    "mcp-health-exporter":   [],
    "kc-exporter":           ["key-custodian"],
    # Telegram bots need hub for alert aggregation
    "notebook-scanner-bot":  ["telegram-hub"],
    "asi360-field-bot":      ["telegram-hub"],
    # Sync needs vault
    "wj-sync":               ["key-custodian"],
}

# ── Tool → Service Mapping (for wake-on-call) ─────────────────────
# Maps MCP tool name prefixes to circuit breaker service IDs.

TOOL_SERVICE_MAP = {
    "mcp__designer-mcp__":    "designer-agent",
    "mcp__firecrawl-mcp__":   "firecrawl-mcp",
    "mcp__mapbox-mcp__":      "mapbox-mcp",
    "mcp__boldsign__":        "boldsign-agent",
    "mcp__docker__":          "500gl-orchestrator-ws",
    "mcp__orchestrator-mcp__":"500gl-orchestrator-ws",
    "mcp__gateway-mcp__":     "mcp-gateway",
    "mcp__athena-mcp__":      "500gl-orchestrator-aseagi",
}

# ── Service Registry ───────────────────────────────────────────────

SERVICES = [
    # ══════════════════════════════════════════════════════════════
    # ALWAYS_ON — Core infrastructure, 24/7, auto-restart
    # ══════════════════════════════════════════════════════════════
    {
        "id": "mcp-gateway",
        "name": "MCP Gateway",
        "description": "Primary HTTP/SSE router for all Claude MCP tool calls",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8443,
        "health_url": "http://127.0.0.1:8443/health",
        "run_type": "systemd",
        "systemd_unit": "mcp-gateway.service",
        "run_mode": "always_on",
        "critical": True,       # Runs even in vacation mode
        "group": "gateway",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 6,
        "function_tags": ["routing", "auth", "rate-limiting", "sse"],
        "prom_metric": 'mcp_server_up{name="mcp-gateway"}',
    },
    {
        "id": "gateway-mcp-http",
        "name": "Gateway MCP HTTP",
        "description": "HTTP transport for direct (non-SSE) tool calls",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8446,
        "health_url": "http://127.0.0.1:8446/health",
        "run_type": "systemd",
        "systemd_unit": "gateway-mcp-http.service",
        "run_mode": "always_on",
        "critical": True,
        "group": "gateway",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 8,
        "estimated_startup_s": 5,
        "function_tags": ["routing", "http-transport"],
        "prom_metric": 'mcp_server_up{name="gateway-mcp-http"}',
    },
    {
        "id": "key-custodian",
        "name": "Key Custodian",
        "description": "Secrets broker — all services fetch API keys via this",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9500,
        "health_url": "http://127.0.0.1:9500/health",
        "run_type": "systemd",
        "systemd_unit": "key-custodian.service",
        "run_mode": "always_on",
        "critical": True,
        "group": "security",
        "cb_failure_threshold": 3,
        "cb_cooldown_s": 60,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 3,
        "startup_grace_s": 5,
        "estimated_startup_s": 3,
        "function_tags": ["security", "vault", "secrets"],
        "prom_metric": None,
    },
    {
        "id": "telegram-hub",
        "name": "Telegram Hub",
        "description": "Central alert aggregator — Prometheus alerts flow here",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9501,
        "health_url": "http://127.0.0.1:9501/health",
        "run_type": "systemd",
        "systemd_unit": "telegram-hub.service",
        "run_mode": "always_on",
        "critical": True,
        "group": "comms",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 5,
        "estimated_startup_s": 4,
        "function_tags": ["alerts", "telegram", "aggregation"],
        "prom_metric": 'mcp_server_up{name="telegram-hub"}',
    },
    {
        "id": "notebook-scanner-bot",
        "name": "Notebook Scanner Bot",
        "description": "Telegram @Don_WJ_OOC_ASI3360_bot — voice/text notebook",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": None,
        "health_url": None,
        "run_type": "systemd",
        "systemd_unit": "notebook-scanner-bot.service",
        "run_mode": "always_on",
        "critical": False,       # NOT critical — sleeps in vacation mode
        "group": "background",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 8,
        "estimated_startup_s": 5,
        "function_tags": ["telegram", "voice", "notebook"],
        "prom_metric": 'mcp_server_up{name="notebook-scanner-bot"}',
    },
    {
        "id": "asi360-field-bot",
        "name": "ASI360 Field Bot",
        "description": "Telegram field capture — photos, GPS, job docs",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9511,
        "health_url": None,
        "run_type": "systemd",
        "systemd_unit": "asi360-field-bot.service",
        "run_mode": "always_on",
        "critical": False,
        "group": "background",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 10,
        "estimated_startup_s": 6,
        "function_tags": ["telegram", "field", "photos"],
        "prom_metric": None,
    },
    {
        "id": "wj-sync",
        "name": "WJ Sync",
        "description": "Supabase → Airtable bi-directional sync (5-min cron)",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9108,
        "health_url": None,
        "run_type": "systemd",
        "systemd_unit": "wj-sync.service",
        "run_mode": "always_on",
        "critical": False,
        "group": "background",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 5,
        "estimated_startup_s": 4,
        "function_tags": ["sync", "airtable", "supabase"],
        "prom_metric": None,
    },

    # ══════════════════════════════════════════════════════════════
    # ON_DEMAND — Start when called, hibernate when idle
    # ══════════════════════════════════════════════════════════════
    {
        "id": "designer-agent",
        "name": "Designer Agent",
        "description": "WordPress page building, content generation, site scraping",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8205,
        "health_url": "http://127.0.0.1:8205/health",
        "run_type": "systemd",
        "systemd_unit": "designer-agent.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,     # 10 min idle → hibernate
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 15,
        "estimated_startup_s": 8,
        "function_tags": ["wordpress", "content", "scraping", "ai"],
        "prom_metric": 'mcp_server_up{name="designer-agent"}',
    },
    {
        "id": "firecrawl-mcp",
        "name": "Firecrawl API",
        "description": "Self-hosted web scraping: scrape, crawl, search, extract",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 3005,
        "health_url": "http://127.0.0.1:3005/health",
        "run_type": "docker",
        "container": "500gl-firecrawl-api",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 900,     # 15 min — Docker startup is slower
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 20,
        "estimated_startup_s": 15,
        "function_tags": ["scraping", "research", "docker"],
        "prom_metric": None,
    },
    {
        "id": "mapbox-mcp",
        "name": "Mapbox MCP",
        "description": "Geocoding, style management, tile queries, GeoJSON",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": None,
        "health_url": None,
        "run_type": "docker",
        "container": "mapbox-mcp",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 15,
        "estimated_startup_s": 12,
        "function_tags": ["maps", "geo", "docker"],
        "prom_metric": 'mcp_server_up{name="mapbox-mcp"}',
    },
    {
        "id": "vtiger-api",
        "name": "VTiger API",
        "description": "REST proxy for VTiger CRM: quotes, projects, tasks, tickets",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 3004,
        "health_url": "http://127.0.0.1:3004/health",
        "run_type": "docker",
        "container": "500gl-vtiger-api",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 900,
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 15,
        "estimated_startup_s": 10,
        "function_tags": ["crm", "docker"],
        "prom_metric": None,
    },
    {
        "id": "boldsign-agent",
        "name": "BoldSign Agent",
        "description": "Document signing + PMA workflows",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8310,
        "health_url": "http://127.0.0.1:8310/health",
        "run_type": "systemd",
        "systemd_unit": "boldsign-agent.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 6,
        "function_tags": ["documents", "signing"],
        "prom_metric": None,
    },
    {
        "id": "500gl-orchestrator-ws",
        "name": "500GL Orchestrator",
        "description": "Food hall ops: checkout, parking, orders, vendors, weather",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8200,
        "health_url": "http://127.0.0.1:8200/health",
        "run_type": "docker",
        "container": "500gl-orchestrator",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 900,
        "group": "orchestration",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 25,
        "estimated_startup_s": 20,
        "function_tags": ["orchestration", "ops", "docker"],
        "prom_metric": 'mcp_server_up{name="500gl-orchestrator"}',
    },
    {
        "id": "weather-jockey",
        "name": "Weather Jockey",
        "description": "Weather briefing service",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8201,
        "health_url": "http://127.0.0.1:8201/health",
        "run_type": "docker",
        "container": "weather-jockey",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 300,     # 5 min — lightweight
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 5,
        "function_tags": ["weather", "docker"],
        "prom_metric": None,
    },

    # ══════════════════════════════════════════════════════════════
    # ON_DEMAND COMMS — Phone/voice systems, wake on webhook
    # ══════════════════════════════════════════════════════════════
    {
        "id": "twilio-mcp",
        "name": "Twilio MCP",
        "description": "SMS notifications, bulk messaging, webhook management",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8091,
        "health_url": "http://127.0.0.1:8091/health",
        "run_type": "systemd",
        "systemd_unit": "twilio-mcp.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,
        "group": "comms",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 5,
        "function_tags": ["sms", "voice", "webhooks"],
        "prom_metric": 'mcp_server_up{name="twilio-mcp"}',
    },
    {
        "id": "telnyx-mcp",
        "name": "Telnyx MCP",
        "description": "SIP/PSTN voice routing, carrier-grade telephony",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8093,
        "health_url": "http://127.0.0.1:8093/health",
        "run_type": "systemd",
        "systemd_unit": "telnyx-mcp.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,
        "group": "comms",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 5,
        "function_tags": ["sip", "voice", "telephony"],
        "prom_metric": None,
    },
    {
        "id": "elevenlabs-mcp",
        "name": "ElevenLabs MCP",
        "description": "AI voice synthesis, IVR voices, audio processing",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8092,
        "health_url": "http://127.0.0.1:8092/health",
        "run_type": "systemd",
        "systemd_unit": "elevenlabs-mcp.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 300,
        "group": "comms",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 5,
        "function_tags": ["voice", "ai", "ivr"],
        "prom_metric": None,
    },
    {
        "id": "woocommerce-mcp",
        "name": "WooCommerce MCP",
        "description": "E-commerce: orders, products, inventory management",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8090,
        "health_url": "http://127.0.0.1:8090/health",
        "run_type": "systemd",
        "systemd_unit": "woocommerce-mcp.service",
        "run_mode": "on_demand",
        "critical": False,
        "idle_timeout_s": 600,
        "group": "tools",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 5,
        "function_tags": ["ecommerce", "orders", "products"],
        "prom_metric": None,
    },

    # ══════════════════════════════════════════════════════════════
    # ALWAYS_ON — Monitoring (must be up to observe others)
    # ══════════════════════════════════════════════════════════════
    {
        "id": "prometheus",
        "name": "Prometheus",
        "description": "Metrics collection — 28 scrape targets, 60d retention",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9090,
        "health_url": "http://127.0.0.1:9090/-/healthy",
        "run_type": "docker",
        "container": "prometheus",
        "run_mode": "always_on",
        "critical": True,
        "group": "monitoring",
        "cb_failure_threshold": 3,
        "cb_cooldown_s": 60,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 8,
        "function_tags": ["metrics", "tsdb", "docker"],
        "prom_metric": None,  # Can't monitor itself via itself
    },
    {
        "id": "grafana",
        "name": "Grafana",
        "description": "Dashboards — CEO Command Center, Sentinel, Infra",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9000,
        "health_url": "http://127.0.0.1:9000/api/health",
        "run_type": "docker",
        "container": "grafana",
        "run_mode": "always_on",
        "critical": True,
        "group": "monitoring",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 15,
        "estimated_startup_s": 10,
        "function_tags": ["dashboards", "visualization", "docker"],
        "prom_metric": 'mcp_server_up{name="grafana"}',
    },
    {
        "id": "alertmanager",
        "name": "Alertmanager",
        "description": "Alert routing to Telegram — critical + warning channels",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9093,
        "health_url": "http://127.0.0.1:9093/-/healthy",
        "run_type": "docker",
        "container": "alertmanager",
        "run_mode": "always_on",
        "critical": True,
        "group": "monitoring",
        "cb_failure_threshold": 3,
        "cb_cooldown_s": 60,
        "max_restart_attempts": 5,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 5,
        "estimated_startup_s": 3,
        "function_tags": ["alerts", "telegram", "docker"],
        "prom_metric": None,
    },
    {
        "id": "mcp-health-exporter",
        "name": "MCP Health Exporter",
        "description": "Prometheus metrics for all MCP servers and ports",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9106,
        "health_url": "http://127.0.0.1:9106/health",
        "run_type": "systemd",
        "systemd_unit": "mcp-health-exporter.service",
        "run_mode": "always_on",
        "critical": True,
        "group": "monitoring",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 5,
        "estimated_startup_s": 3,
        "function_tags": ["metrics", "health"],
        "prom_metric": None,
    },
    {
        "id": "kc-exporter",
        "name": "KC Exporter",
        "description": "Key Custodian vault audit metrics for Prometheus",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 9104,
        "health_url": None,
        "run_type": "systemd",
        "systemd_unit": "kc-exporter.service",
        "run_mode": "always_on",
        "critical": False,
        "group": "monitoring",
        "cb_failure_threshold": 5,
        "cb_cooldown_s": 300,
        "max_restart_attempts": 3,
        "restart_backoff_base_s": 10,
        "startup_grace_s": 5,
        "estimated_startup_s": 3,
        "function_tags": ["metrics", "vault"],
        "prom_metric": None,
    },

    # ══════════════════════════════════════════════════════════════
    # MANUAL — Staging / dev / analytics
    # ══════════════════════════════════════════════════════════════
    {
        "id": "mcp-gateway-staging",
        "name": "Gateway Staging",
        "description": "Pre-production testing of gateway changes",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 8445,
        "health_url": "http://127.0.0.1:8445/health",
        "run_type": "systemd",
        "systemd_unit": "mcp-gateway-staging.service",
        "run_mode": "manual",
        "critical": False,
        "group": "gateway",
        "cb_failure_threshold": 3,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 2,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 10,
        "estimated_startup_s": 6,
        "function_tags": ["staging"],
        "prom_metric": 'mcp_server_up{name="mcp-gateway-staging"}',
    },
    {
        "id": "duckdb-mcp",
        "name": "DuckDB MCP",
        "description": "Analytics queries on WhatsApp conversation data",
        "droplet": "workspace",
        "host": "104.248.69.86",
        "port": 3100,
        "health_url": None,
        "run_type": "systemd",
        "systemd_unit": "duckdb-mcp.service",
        "run_mode": "manual",
        "critical": False,
        "group": "tools",
        "cb_failure_threshold": 3,
        "cb_cooldown_s": 120,
        "max_restart_attempts": 2,
        "restart_backoff_base_s": 5,
        "startup_grace_s": 5,
        "estimated_startup_s": 3,
        "function_tags": ["analytics", "sql"],
        "prom_metric": None,
    },
]

SERVICE_MAP = {s["id"]: s for s in SERVICES}

# ── Derived: Services by mode ──────────────────────────────────────
ALWAYS_ON_SERVICES = [s for s in SERVICES if s["run_mode"] == "always_on"]
ON_DEMAND_SERVICES = [s for s in SERVICES if s["run_mode"] == "on_demand"]
MANUAL_SERVICES = [s for s in SERVICES if s["run_mode"] == "manual"]
CRITICAL_SERVICES = [s for s in SERVICES if s.get("critical", False)]

# ── Vacation mode: only critical services run ──────────────────────
VACATION_KEEP_ALIVE = [s["id"] for s in CRITICAL_SERVICES]
